development:
  adapter: postgresql
  encoding: unicode
  database: espanol_development
  pool: 5
  username: jack
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: espanol_test
  pool: 5
  username: jack
  password:
